-- XoloDojo — Supabase schema (auth.users + profiles + wallet sessions)
-- Run in Supabase Dashboard → SQL Editor → New query → Run
--
-- Hybrid auth:
--   • Email/password → Supabase Auth (auth.users) + public.profiles
--   • Wallet-only     → public.wallet_sessions + xolodojo_wallet_session cookie
--
-- API server uses SUPABASE_SERVICE_ROLE_KEY and bypasses RLS.

-- ---------------------------------------------------------------------------
-- profiles (1:1 with auth.users)
-- ---------------------------------------------------------------------------
create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  username varchar(32) not null,
  name varchar(255),
  role varchar(32) not null default 'user',
  picture_url text,
  bio text,
  wallet_address varchar(255),
  wallet_type varchar(50),
  connected_wallet_id integer,
  preferences jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_profiles_username unique (username)
);

create index idx_profiles_username_lower on public.profiles (lower(username));
create index idx_profiles_wallet_address on public.profiles (wallet_address);
create index idx_profiles_connected_wallet_id on public.profiles (connected_wallet_id);

comment on table public.profiles is 'App profile; id matches auth.users. Email lives on auth.users.';

-- ---------------------------------------------------------------------------
-- wallet_sessions — cookie sessions for wallet-only sign-in (no auth.users row)
-- ---------------------------------------------------------------------------
create table public.wallet_sessions (
  id uuid primary key default gen_random_uuid(),
  wallet_address varchar(255) not null,
  wallet_type varchar(50) not null,
  token_hash char(64) not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  constraint uq_wallet_sessions_token_hash unique (token_hash)
);

create index idx_wallet_sessions_wallet on public.wallet_sessions (wallet_address);
create index idx_wallet_sessions_expires on public.wallet_sessions (expires_at);

-- ---------------------------------------------------------------------------
-- user_wallets
-- ---------------------------------------------------------------------------
create table public.user_wallets (
  id integer generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  wallet_address varchar(255) not null,
  wallet_type varchar(50) not null,
  is_connected boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_user_wallets_user_wallet unique (user_id, wallet_address)
);

create index idx_user_wallets_user_id on public.user_wallets (user_id);
create index idx_user_wallets_wallet_address on public.user_wallets (wallet_address);
create index idx_user_wallets_is_connected on public.user_wallets (is_connected);

-- ---------------------------------------------------------------------------
-- user_pins — XoloGlobe map pins
-- ---------------------------------------------------------------------------
create table public.user_pins (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles (id) on delete cascade,
  token_id varchar(512) not null,
  wallet_address varchar(255) not null,
  issuer varchar(255),
  uri text,
  latitude numeric(10, 7) not null,
  longitude numeric(10, 7) not null,
  image_url text,
  title varchar(512),
  collection_name varchar(512),
  socials jsonb,
  pin_note text,
  pinned_at timestamptz(3) not null default now(),
  created_at timestamptz(3) not null default now(),
  updated_at timestamptz(3) not null default now()
);

create unique index uq_user_pins_wallet_token on public.user_pins (wallet_address, token_id);
create index idx_user_pins_user_id on public.user_pins (user_id);
create index idx_user_pins_pinned_at on public.user_pins (pinned_at);

-- ---------------------------------------------------------------------------
-- globe_pin_bookmarks
-- ---------------------------------------------------------------------------
create table public.globe_pin_bookmarks (
  id bigint generated by default as identity primary key,
  account_key varchar(300) not null,
  token_id varchar(512) not null,
  created_at timestamptz(3) not null default now()
);

create unique index uq_globe_pin_bookmark on public.globe_pin_bookmarks (account_key, token_id);
create index idx_globe_pin_bookmark_account on public.globe_pin_bookmarks (account_key);

-- ---------------------------------------------------------------------------
-- updated_at triggers
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

create trigger user_wallets_set_updated_at
  before update on public.user_wallets
  for each row execute function public.set_updated_at();

create trigger user_pins_set_updated_at
  before update on public.user_pins
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Auto-create profile on sign-up (username + name from user_metadata)
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  meta_username text;
  meta_name text;
  fallback_username text;
begin
  meta_username := nullif(trim(new.raw_user_meta_data->>'username'), '');
  meta_name := coalesce(
    nullif(trim(new.raw_user_meta_data->>'name'), ''),
    nullif(trim(new.raw_user_meta_data->>'display_name'), '')
  );
  fallback_username := split_part(coalesce(new.email, 'user'), '@', 1);

  insert into public.profiles (id, username, name)
  values (
    new.id,
    coalesce(meta_username, fallback_username),
    meta_name
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- Row Level Security (API uses service role; blocks direct anon access)
-- ---------------------------------------------------------------------------
alter table public.profiles enable row level security;
alter table public.wallet_sessions enable row level security;
alter table public.user_wallets enable row level security;
alter table public.user_pins enable row level security;
alter table public.globe_pin_bookmarks enable row level security;

create policy "Profiles are readable by everyone"
  on public.profiles for select using (true);

create policy "Users can update own profile"
  on public.profiles for update using (auth.uid() = id);

create policy "Globe pins are readable by everyone"
  on public.user_pins for select using (true);

-- ---------------------------------------------------------------------------
-- Role grants (required for service_role API access + public read policies)
-- ---------------------------------------------------------------------------
grant usage on schema public to postgres, anon, authenticated, service_role;

grant all on all tables in schema public to postgres, service_role;
grant all on all sequences in schema public to postgres, service_role;
grant all on all routines in schema public to postgres, service_role;

grant select on all tables in schema public to anon, authenticated;

alter default privileges in schema public
  grant all on tables to postgres, service_role;

alter default privileges in schema public
  grant all on sequences to postgres, service_role;

alter default privileges in schema public
  grant all on routines to postgres, service_role;

alter default privileges in schema public
  grant select on tables to anon, authenticated;

grant all on table public.profiles to service_role;
grant all on table public.wallet_sessions to service_role;
grant all on table public.user_wallets to service_role;
grant all on table public.user_pins to service_role;
grant all on table public.globe_pin_bookmarks to service_role;

grant select on table public.profiles to anon, authenticated;
grant select on table public.user_pins to anon, authenticated;

grant execute on function public.set_updated_at() to service_role;
grant execute on function public.handle_new_user() to service_role;
